### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DeadShot83** [rebelmuffin/DiscordIRCBridge#1]
Traceback (most recent call last):
  File "main.py", line 79, in <module>
    discord_bot.run(TOKEN)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 755, in run
    return future.result()
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 734, in runner
    await self.start(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 697, in start
    await self.login(*args)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 544, in login
    await self.http.static_login(token.strip())
  File "/home/pi/.local/lib/python3.7/site-packages/discord/http.py", line 303, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.

**Comment by rebelmuffin** [comment]
Hello, `LoginFailure` means that wrong credentials were passed into `Client.run()`. Could you check and confirm that your token is valid?
